version: "3.8"
services:

  lab5-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - ADMIN_PASSWORD=passwordToSet
      - FRONTEND_URL_PROTOCOL=http://
      - FRONTEND_URL_DOMAIN_NAME=localhost
      - FRONTEND_URL_PORT=80
    depends_on:
      - lab5-db
    labels:
      - traefik.enable=true
      - traefik.http.routers.lab5-server.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.web.loadbalancer.server.port=5000
      - traefik.http.services.api.loadBalancer.sticky.cookie=true
      - traefik.http.services.api.loadBalancer.sticky.cookie.name=api-cookie

  lab5-web-site:
    build:
      context: ./web/site
      dockerfile: Dockerfile
    depends_on:
      - lab5-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.lab5-web-site.rule=Host(`localhost`)
      - traefik.http.services.web.loadbalancer.server.port=80

  lab5-db: #thanks to : https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md
    image: bitnami/postgresql:latest
    container_name: lab5-db
    environment:
      - POSTGRESQL_USERNAME=u_app
      - POSTGRESQL_PASSWORD=super_secret
      - POSTGRESQL_DATABASE=db_app
    volumes:
      - psql:/bitnami/postgresql
    ports:
      - 3306:5432
    labels:
      - traefik.enable=false

  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true  # Enable Traefik dashboard
      - --providers.docker
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard

volumes:
  psql:

#docker-compose up  --force-recreate -d
#docker-compose down
