version: "3.8"
services:
  lab5-web-site:
    build:
      context: ./web/site
      dockerfile: Dockerfile
    container_name: lab5-web-site
    ports:
      - 80:80
    depends_on:
      - lab5-server
    networks:
      - lab5-web-site

  lab5-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lab5-server
    environment:
      - PORT=7000
      - ADMIN_PASSWORD=passwordToSet
      - FRONTEND_URL_PROTOCOL=http://
      - FRONTEND_URL_DOMAIN_NAME=localhost
      - FRONTEND_URL_PORT=80
    ports:
      - 7000:7000
    depends_on:
      - lab5-db
    networks:
      - lab5-server
      - lab5-web-site
      - lab5-db

  lab5-db: #thanks to : https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md
    image: bitnami/postgresql:latest
    container_name: lab5-db
    environment:
      - POSTGRESQL_USERNAME=u_app
      - POSTGRESQL_PASSWORD=super_secret
      - POSTGRESQL_DATABASE=db_app
    volumes:
      - psql:/bitnami/postgresql
    ports:
      - 3306:3306
    networks:
      - lab5-db

volumes:
  psql:

networks:
  lab5-server:
    name: lab5-server
    driver: bridge
  lab5-web-site:
  lab5-db:

#docker-compose up  --force-recreate -d
#docker-compose down
