version: "3.8"
services:
  lab5-web-site:
    build:
      context: ./web/site
      dockerfile: Dockerfile
    container_name: lab5-web-site
    ports:
      - 8080:80
    depends_on:
      - lab5-server
    networks:
      - lab5-web-site

  lab5-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lab5-server
    environment:
      - PORT=5000
      - ADMIN_PASSWORD=passwordToSet
      - FRONTEND_URL_PROTOCOL=http://
      - FRONTEND_URL_DOMAIN_NAME=localhost
      - FRONTEND_URL_PORT=8080
    ports:
      - 5000:80
    networks:
      - lab5-server
      - lab5-web-site
networks:
  lab5-server:
    name: lab5-server
    driver: bridge
  lab5-web-site:

#docker-compose up  --force-recreate -d
#docker-compose down
